### ISSUE TITLE
Alternative (free) installation method

### ISSUE THREAD

**Issue by jsimonetti** [asmaloney/GuildWars2-macOS#10]
### macOS Version

Sonoma 14.3 M3 Pro

### WineskinServer Version

not applicable

### Wine Engine Version

latest crossover wine

### Problem

None, other then I do not own Crossover.

### Additional Information

# install prerequisites (this asumes you have brew installed)
$ brew install winetricks
$ brew install --cask gcenx/wine/wine-crossover

# set the base wine prefix
$ export WINEPREFIX=~/'WinePrefix/GW2'

# configure prefix for windows 10
$ winetricks win10

# download and extract latest DXVK from https://github.com/Gcenx/DXVK-macOS/releases

$ cp x64/\*.dll $WINEPREFIX/drive_c/windows/system32
$ cp x32/\*.dll $WINEPREFIX/drive_c/windows/syswow64

# configure dxvk
$ winecfg

# under libraries add the following overrides:
 - d3d10core (native, builtin)
 - d3d11 (native,builtin)
 - d3d9 (native, builtin)
 - dxgi (builtin, native)

# download GW2 setup

$ cp Gw2Setup-64.exe $WINEPREFIX/drive_c/

# install GW2 like regular
$ wine "C:\\\\Gw2Setup-64.exe"

# optional launcher:
$ mkdir -p ~/Applications/GW2.app/Contents/MacOS
$ vi ~/Applications/GW2.app/Contents/Info.plist
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><plist version="1.0">
  <dict>
    <key>CFBundleExecutable</key>
    <string>GW2</string>
    <key>CFBundleGetInfoString</key>
    <string>GW2</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
</dict>
</plist>
```

$ vi ~/Applications/GW2.app/Contents/MacOS/GW2
```sh
#!/bin/sh
WINEPREFIX=~/'WinePrefix/GW2' exec wine "C:\\Program Files\\Guild Wars 2\\Gw2-64.exe"
```
$ chmod +x ~/Applications/GW2.app/Contents/MacOS/GW2

## You can add an icon using the Apple Finder
 - navigate to ~/Applications
 - right click GW2.app and select 'Get info'
 - select the icon in the top left next to 'GW2.app' and 'Modified: ...' (should be a white square by default)
 - paste a desired icon file (you can copy the image from preview or any other desired application)

**Comment by asmaloney** [comment]
Thanks!
