### ISSUE TITLE
Stuck in Initailizing stage screen

### ISSUE THREAD

**Issue by GeorgeH9292** [asmaloney/GuildWars2-macOS#3]
I have followed all of the configuration options to setup a new wine wrapper, it all sets up correctly and finishes the wine trick config.
I choose the relevant gw2.exe file in my documents area, it starts to download on the first loading screen and then gets stuck on initialising screen and the wine skin wrapper goes into 'not responding' mode. This happens every time regardless of what I do, please help.
This had been working fine and runs so well on my MacBook Pro 2021 M1, I have been forced to GeForceNow and it's just not running well consistently due to network connectivity.

**Comment by asmaloney** [comment]
George:

Hopefully good news for you (for now)!

The Guild Wars 2 [update from 18 April](https://en-forum.guildwars2.com/topic/129939-game-update-notes-april-18-2023/) turned on the [Chromium Embedded Framework](https://en.wikipedia.org/wiki/Chromium_Embedded_Framework) (CEF) as a replacement for the _Coherent UI_ - which is what they use for various parts of the interface including the storefront. This broke things for those of us using (some versions?) of WINE.

Thankfully there is a way to work around it by using a [command line argument](https://wiki.guildwars2.com/wiki/Command_line_arguments) to force GW2 to use the older Coherent UI.

- open up your GW2 Wineskin
- choose the _Advanced_ options
- at the top where the **Windows app** is set, add `-usecoherent` to the command line

<img width="685" alt="Screen Shot 2023-05-03 at 15 11 08 PM" src="https://user-images.githubusercontent.com/391371/236021073-c443b49d-c7e3-4acb-a4c7-9a381336ef18.png">

This works for me - _for now_.

I've tried various ways to get CEF to work without any luck. So if ANet decides to go "all in" on CEF and remove this option, we may have a problem...

Please let me know if that gets you back into Tyria.

**Comment by GeorgeH9292** [comment]
Will this work for the step before the program files are installed? I have started a new wrapper and the program files aren’t installed yet.

**Comment by asmaloney** [comment]
I just tried it from scratch & I think it'll work.

I downloaded the latest installer [from here](https://account.arena.net/welcome).

I let it reach the point where it starts to download all the data (just before the **Copying The Data File From An Old Installation** section in the guide) and it was fine.

**Edit:** I just completed the installation and it works after adding the `-usecoherent` option.

**Comment by GeorgeH9292** [comment]
Ok, so if I get it to start the download and then close it, before it gets stuck at initializing?

would you be able to provide me with some updated steps to follow at all? Or some screenshots?

**Comment by asmaloney** [comment]
The differences from the instructions in the post:

- I ran the installer _before_ I added the **Winetricks** for dxvk and win10 (not sure if this matters or not?)
- I added the `-usecoherent` option once all the data was installed or copied over

**Comment by GeorgeH9292** [comment]
I can’t get to the stage where gw2 is fully installed after choosing the gw2.exe file, when picking the executable

**Comment by GeorgeH9292** [comment]
I get to the steps where wrapper is created, 7zip is run and then I select the dxvk1102 and win10 and click run. After this I then choose the executable to be installed from my documents. It is at this step, it starts to download and then gets stuck at initializing stage prior to loading up the main gw2 window where I can click the install button and create the program files area.

**Comment by asmaloney** [comment]
OK then maybe the order does matter. Try switching the order of running the installer and installing the winetricks like I mention above.

**Comment by GeorgeH9292** [comment]
Ok so complete the 7zip step but not the next steps and choose executable after 7zip update? Or choose executable after creating wrapper and then follow the steps?

**Comment by asmaloney** [comment]
There is no 7zip step. Make sure you are [following the right document](https://asmaloney.com/2022/07/howto/running-guild-wars-2-with-dx11-on-macos-using-wine/).

Run the two winetricks after running the GW2 installer and everything is in place. This will enable DX11. I suspect that the CEF probably happens to work when DX11 is _not_ installed, but then when we install DX11 (since it's required by GW2 now) it borks CEF.

**Comment by GeorgeH9292** [comment]
That has allowed me to get to the install button thank you. I will close after it's running after finishing wrapper setup

**Comment by GeorgeH9292** [comment]
thank you for all of your help, I wish I had raised this issue straight away, could have saved myself 26.99 instead of ending up using GeForceNow thinking it would not be able to get sorted

**Comment by asmaloney** [comment]
Glad you got going again. I will reorder the document to do winetricks after the main installation.

Unfortunately we are going to have a problem if/when ANet forces CEF as I have not found a solution...
