### ISSUE TITLE
GW2 will not start post Coherent/Chromium Embedded change

### ISSUE THREAD

**Issue by a3w275** [asmaloney/GuildWars2-macOS#4]
I started with a clean installation using your DX.11 instructions. Here is a screenshot with my set up info:
<img width="983" alt="Screenshot 2023-05-09 at 5 33 53 PM" src="https://github.com/asmaloney/GuildWars2-macOS/assets/133062095/b6eaf3bb-b2a3-4287-8126-5cd631c70e89">

Using "dxvk1103_macOS" under wine tricks. 

When I start the app/package is the the "downloading" screen flash up for a moment, and then a new screen with the message "initializing  . . ." then that disappears and there is nothing. Activity monitor shows 8 wine64-preloader processes along with winserver, but no game login screen. 

The exact same set up using the -usecoherent command argument will get me to a full login screen. However once I login I have a full black screen that eventually disappears.

I have a second Mac that is a MacBook Pro with the same GW2/WINE set up but I haven't upgraded to Ventura, it's still running Big Sur. On that computer I have the same problem when just using the executable without the -usecoherent command argument, but with that argument the game remains playable. Any suggestions?

**Comment by asmaloney** [comment]
1. I haven't got macOS 13 installed - only 12.6.5 - so I don't know if that's a factor.
2. The `-usecoherent` option is absolutely required at this time as CEF just doesn't work. (I notice it's not set in the image you included.)
3. For the black screen issue - I wonder if it's a windowed/fullscreen issue? You can try adding `-windowed` to that command line as well to start in windowed mode. Once it's running you can switch between windowed and fullscreen using <kbd>Option</kbd>+<kbd>Return</kbd>.
4. Your Wineskin Wrapper is at **2.9.1.1**. You might try updating that to the latest **2.9.1.9**. You can do this by running _Wineskin Winery_ again and updating the wrapper version, then running _Wineskin_ for your GW2 install and clicking **Update Wrapper** under the Tools section.
5. Your Engine is also out of date. You can update it much the same way as the wrapper in (4). I'm using **WS11WineCX64Bit22.0.1-2**.

**Comment by a3w275** [comment]
Thank you. I hadn't (and should have) noticed that those were out of date. I really HAD checked your webpage to see if you had updates regarding the CEF but that was over a week ago and just caught that you added an update a couple days ago. I downloaded the updated versions of everything and built a new wrapper with the updated engine and am back to being able to login to the game. Would it be beneficial to remove those other older engines from the winery?

**Comment by asmaloney** [comment]
Praise Joko! Glad you got going again.

> you added an update a couple days ago.

👍  Yes - that CEF stuff is unfortunate. I hope ANet leaves the `-usecoherent` option in...

> Would it be beneficial to remove those other older engines from the winery?

They won't affect anything, but I tend to remove them if I'm not using them.
