### ISSUE TITLE
GW2 Game Client Crashing

### ISSUE THREAD

**Issue by GeorgeH9292** [asmaloney/GuildWars2-macOS#6]
My game client has been crashing of late, it tends to mostly happen in pop, my MacBook Pro 2021 model is top spec, but obviously gets hot, after all GW2 is a graphic heavy game, and laptops aren't necessarily built for gaming, however I have noticed that there are specific situations when's my game client crashes, and for some reason that is either mid game in pvp or just as you've won the match.

Any ideas on how I can improve this?

As soon as GW2 client is closed, my MacBook immediately starts to cool down, and I try again or reload the game client and all is fine, until it crashes again depending on what I'm doing.

Due to this I'm actually worried about going into RAIDs in case I crash.

**Comment by asmaloney** [comment]
Unfortunately I don't have any real suggestions here.

I believe GW2 is CPU heavy (as opposed to GPU) which is probably why it heats up so much. On my iMac, the fans start up full throttle when I run GW2 as well. I have played it on a MacBook Pro (2016), but that was with the official client years ago.

Overall for me, the game has been pretty stable in terms of crashes - probably average one a month or so (playing daily). So it might just be heat related? Can you put it on a stand and/or point an external fan at it for better airflow? 😄

> Due to this I'm actually worried about going into RAIDs in case I crash.

I understand. I crashed once during raids and felt pretty bad 😞 

Oh - are you running ArcDPS (or other tools like it)? Maybe try without it if you are?

**Comment by GeorgeH9292** [comment]
What is ArcDPS? I mainly have safari browser up.

I'm going to look at getting a cooling stand for my Mac, which will hopefully help, as the feet on the MacBook Pros are so small that they barely lift it off the desk ha.

**Comment by asmaloney** [comment]
> What is ArcDPS?

Ah - when you mentioned raids I thought you might use a tool like ArcDPS which is for showing real-time combat metrics (like... DPS, boons, etc.) for your party on screen as an overlay to the game. It can cause problems (i.e. crashes) when the version is out-of-sync with the game client.

> the feet on the MacBook Pros are so small that they barely lift it off the desk

Exactly. Sometimes when I'm lying down watching a video with mine, it heats up like crazy and the fans go wild. I set it on a cork yoga block and it calms down 😆

**Comment by GeorgeH9292** [comment]
Oh no I don't use any overlay apps.

I wonder why mine crashes so much compared with yours, I think it may likely be an over heating issue.

**Comment by GeorgeH9292** [comment]
Well strangely I used my new lvl80 exp boost for a new warrior character to get ready for expansion, and it ran so smooth its crazy, no crashes...touch wood whatsoever, even in dragon stand. So maybe there is something I was doing in the background which was super heating my MacBook Pro...I don't know, but was having some good fun bashing the heck out of enemies, with my axes ha

**Comment by asmaloney** [comment]
Praise Joko!

Glad to hear it - have fun out there.

**Comment by GeorgeH9292** [comment]
Do you run a guild or anything? Looking for people to play with, as I don't have many real life friends that play

**Comment by asmaloney** [comment]
I don't, no. Well, I have a one-man guild just so I can play around with the guild hall. 😄 

If there are game modes you play more frequently (fractals, raids, PvP, WvW), then I would suggest finding a guild that's based around those. For example I'm a member of one large guild which does WvW almost exclusively. If you do a bit of everything then yeah it's a little tougher. Your options are basically to chat with others as much as possible to find a guild that fits, use the guild finding thing in the LFG (or respond to one of the many spam messages in chat), or... start your own! There may be external resources for finding guilds as well - like the official forums; maybe some other sites?
