### ISSUE TITLE
useCoherent Crash

### ISSUE THREAD

**Issue by a3w275** [asmaloney/GuildWars2-macOS#7]
### macOS Version

10.13.6

### WineskinServer Version

2.9.1.9

### Wine Engine Version

WS11WineCX64Bit22.1.1-8

### Problem

I'm trying to help a family member log into the client. I updated in May using your instructions and was able to get in, however they haven't used the game since then and tried to log in today and the game crashed. I performed a -repair on the client and then saved the BIN and deleted the wrapper/client and started over. I've (hopefully) followed your instructions and downloaded and rebuilt the wrapper/client with the versions above. The client immediately crashes on login with something having to do with CoherentUI_Host.exe according to the crash dump error log.
  
<img width="1260" alt="Screenshot 2023-07-15 at 3 11 05 PM" src="https://github.com/asmaloney/GuildWars2-macOS/assets/133062095/03b62e0e-d9ac-4785-9057-d010454f6f46">

I have compared this non-functioning wrapper/client against my own that IS presently working and aside from having a slightly different engine (I have 22.1.1-rc2) everything seems to be identical between the two, apart from running different base operating systems. Any suggestions?

**Comment by asmaloney** [comment]
Did that machine work with an older version of the WINE engine? If so you could try backing off to an older one.

> apart from running different base operating systems

I think this is the problem. 10.13 hasn't been supported in a very long time. The setup seems pretty sensitive to the macOS version - I had it crashing on 10.15, but it worked on 10.14 alright.

Right around May, GW2 put out a couple of updates that forced us to use the Coherent fix. It's possible something they did there broke running on older versions of macOS.

**Comment by a3w275** [comment]
Thanks for the quick response. I just tried building a new wrapper using the versions you have listed in the instructions and run into the same problems. I'm going to have to shelve this for the foreseeable future I guess until they are able to get a new computer.
